# MongoDB Configuration
mongo_uri: "mongodb://localhost:27017/"
database: "mongo_db_project"
collection: "dynamic_collection"

# CSV File Paths
files:
  - file_path: "load_database/dynamic/unipi_ais_dynamic_may2017.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_jun2017.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_jul2017.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_aug2017.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_sep2017.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_oct2017.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_nov2017.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_dec2017.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_jan2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_feb2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_mar2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_apr2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_may2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_jun2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_jul2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_aug2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_sep2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_oct2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_nov2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_dec2018.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_dec2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_jan2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_feb2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_mar2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_apr2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_may2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_jun2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_jul2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_aug2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_sep2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_oct2019.csv"
  - file_path: "load_database/dynamic/unipi_ais_dynamic_nov2019.csv"
