mongo_uri: "mongodb://localhost:27017/"
database: "mongo_db_project"
collection: "geodata_collection"

shapefiles:
  - file_path: "harbours/harbours.shp"
    encoding: "ISO-8859-1"
  - file_path: "islands/islands.shp"
    encoding: "ISO-8859-1"
  - file_path: "piraeus_port/piraeus_port.shp"
    encoding: "ISO-8859-1"
  - file_path: "receiver_location/receiver_location.shp"
    encoding: "ISO-8859-1"
  - file_path: "regions/regions.shp"
    encoding: "ISO-8859-7"
  - file_path: "spatial_coverage/spatial_coverage.shp"
    encoding: "ISO-8859-1"
  - file_path: "territorial_waters/saronic_territorial_waters.shp"
    encoding: "ISO-8859-1"
